apiVersion: keystone.openstack.org/v1beta1
kind: KeystoneAPI
metadata:
  name: keystone
spec:
  adminProject: admin
  adminRole: admin
  adminUser: admin
  containerImage: quay.io/tripleotraincentos8/centos-binary-keystone:current-tripleo
  customServiceConfig: |
    [DEFAULT]
      debug = true
  databaseHostname: openstack
  databaseUser: keystone
  debug:
    bootstrap: false
    dbSync: false
    service: false
  preserveJobs: false
  region: regionOne
  replicas: 1
  secret: keystone-secret